services:
  - type: web
    name: rural-whatsapp-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_SHEET_KEY_JSON
        value: (Paste your Google Service JSON here as string)
